# coding:utf-8
import turtle

# define a function to draw a circle
def DrawtheCircle(startx=0, starty=-150, radius=150):
    turtle.penup()
    turtle.goto(startx, starty)
    turtle.pendown()
    turtle.circle(radius)

# define a function to draw the qiushi eagle
def DrawtheEagle(startx = 0, starty = 100, ratio = 1, rotation = 0):

    turtle.penup()
    turtle.goto(startx,starty)
    turtle.pendown()
    turtle.right(rotation)

    turtle.begin_fill()

    turtle.forward(20*ratio)
    turtle.right(5)
    turtle.forward(10*ratio)
    turtle.right(5)
    turtle.forward(30*ratio)
    turtle.right(150)
    turtle.forward(40*ratio)
    turtle.left(90)
    turtle.forward(50*ratio)
    turtle.left(120)
    turtle.forward(60*ratio)
    turtle.right(10)
    turtle.forward(10*ratio)
    turtle.right(40)

    # 1
    turtle.forward(150*ratio)
    turtle.right(150)
    turtle.forward(50*ratio)
    turtle.right(20)
    turtle.forward(10*ratio)
    turtle.right(20)
    turtle.forward(10*ratio)
    turtle.left(10)
    turtle.forward(30*ratio)
    turtle.left(60)
    turtle.forward(25*ratio)
    turtle.left(120)

    turtle.forward(80*ratio)
    turtle.right(150)
    turtle.forward(50*ratio)
    turtle.right(20)
    turtle.forward(10*ratio)
    turtle.right(20)
    turtle.forward(10*ratio)
    turtle.left(10)
    turtle.forward(30*ratio)
    turtle.left(60)
    turtle.forward(25*ratio)
    turtle.left(120)

    turtle.forward(60*ratio)
    turtle.right(150)
    turtle.forward(40*ratio)
    turtle.right(20)
    turtle.forward(10*ratio)
    turtle.right(20)
    turtle.forward(10*ratio)
    turtle.left(10)
    turtle.forward(10*ratio)
    turtle.left(60)
    turtle.forward(25*ratio)
    turtle.left(120)

    turtle.forward(50*ratio)
    turtle.right(140)
    turtle.forward(30*ratio)
    turtle.right(20)
    turtle.forward(10*ratio)
    turtle.right(30)
    turtle.forward(10*ratio)
    turtle.left(10)
    turtle.forward(10*ratio)
    turtle.left(60)
    turtle.forward(25*ratio)
    turtle.left(120)

    turtle.forward(40*ratio)
    turtle.right(140)
    turtle.forward(30*ratio)
    turtle.right(20)
    turtle.forward(10*ratio)
    turtle.right(30)
    turtle.forward(10*ratio)
    turtle.left(10)
    for i in range(10):
        turtle.left(15)
        turtle.forward(4*ratio)

    # 2
    turtle.right(105)
    turtle.forward(90*ratio)
    turtle.right(90)
    turtle.forward(90*ratio)

    # 3
    turtle.right(110)
    for i in range(10):
        turtle.left(15)
        turtle.forward(4*ratio)

    turtle.right(10)
    turtle.forward(10*ratio)
    turtle.right(20)
    turtle.forward(5*ratio)
    turtle.right(20)
    turtle.forward(25*ratio)
    turtle.right(125)
    turtle.forward(40*ratio)

    turtle.left(120)
    turtle.forward(25*ratio)
    turtle.left(60)
    turtle.forward(10*ratio)
    turtle.left(10)
    turtle.forward(10*ratio)
    turtle.right(30)
    turtle.forward(10*ratio)
    turtle.right(20)
    turtle.forward(30*ratio)
    turtle.right(140)
    turtle.forward(50*ratio)

    turtle.left(120)
    turtle.forward(25*ratio)
    turtle.left(60)
    turtle.forward(10*ratio)
    turtle.left(10)
    turtle.forward(10*ratio)
    turtle.right(20)
    turtle.forward(10*ratio)
    turtle.right(20)
    turtle.forward(40*ratio)
    turtle.right(150)
    turtle.forward(60*ratio)

    turtle.left(120)
    turtle.forward(25*ratio)
    turtle.left(60)
    turtle.forward(30*ratio)
    turtle.left(10)
    turtle.forward(10*ratio)
    turtle.right(20)
    turtle.forward(10*ratio)
    turtle.right(20)
    turtle.forward(45*ratio)
    turtle.right(150)
    turtle.forward(80*ratio)

    turtle.left(120)
    turtle.forward(25*ratio)
    turtle.left(60)
    turtle.forward(30*ratio)
    turtle.left(10)
    turtle.forward(10*ratio)
    turtle.right(20)
    turtle.forward(10*ratio)
    turtle.right(20)
    turtle.forward(50*ratio)
    turtle.right(150)
    turtle.forward(150*ratio)

    # 4
    turtle.right(40)
    turtle.forward(10*ratio)
    turtle.right(10)
    turtle.forward(60*ratio)
    turtle.left(125)
    turtle.forward(60*ratio)
    turtle.goto(startx, starty)

    turtle.end_fill()

# Initialize
turtle.pensize(4)
turtle.speed(8)
turtle.pencolor('blue')
turtle.fillcolor('pink')
turtle.hideturtle()

# DrawtheCircle()
DrawtheEagle()
turtle.done()